= 帝範（唐·太宗）
:doctype: japanese-industrial-standard
:docseries: A
:docnumber: 1001
:edition: 1
:language: ja
:published-date: 2025-01-15
:copyright-year: 2025
:announced-date: 2025-01-15
:announced-date-ja: 公曆 2025年1月15日
:revision-date: 2025-01-15
:revision-date-ja: 公曆 2025年1月15日
:establishment-date: 1951-10-31
:establishment-date-ja: 公曆 2025年1月15日
:title-main-ja: 帝範
:title-main-en: The Imperial Model
:imagesdir: images
:coverpage-image: images/coverpage.pdf
:backpage-image: images/backpage.pdf
:presentation-metadata-color-header-footer-background: #0b0968
:presentation-metadata-vertical-layout: true
:presentation-metadata-autonumbering-style: japanese
:toclevels-pdf: 1
:mn-document-class: jis
:mn-output-extensions: xml,html,doc,pdf,rxl
:local-cache-only:
:publisher-ja: 早稲田大学図書館
:publisher-en: Waseda University Library
:publisher-abbr: WUL
:investigative-organization-ja: 欽定四庫全書
:investigative-organization-en: Investigative Committee for the Compilation of the Complete Library in Four Sections
:investigative-committee: 欽定四庫全書
:investigative-committee-representative-name: 酒井 信介
:investigative-committee-representative-role: 部会長
:affiliation: 日本産業標準調査会 標準第一部会
:contributor_position: 委員会長
:source-proposer-name: 一般財団法人日本規格協会

[.preface]
== 欽定四庫全書　子部一 提要 帝範四卷　儒家類

　　〈臣〉等謹按帝範十二篇唐太宗貞觀二十二年撰以賜太子新舊唐書皆云四卷晁公武讀書志僅載六篇陳振孫書録解題亦題曰一卷元吳萊謂征雲南僰夷時始得完書攷其事在泰定二年蓋此書宋佚其半元乃復完也唐書藝文志載有賈行注而舊唐書敬宗本紀稱寳歴二年秘書省著作郎韋公肅注是書以進是唐時已有二注今本注無姓名觀其體裁似唐人注經之式而其中時稱楊萬里呂祖謙之言疑元人因舊注而補之其援引頗詳洽而詞不免於煩贅〈臣〉等謹為參攷其誤附列注文之下仍依舊史釐為四卷以復其舊雲乾隆三十八年四月恭校上

　　總纂官〈臣〉紀昀〈臣〉陸錫熊〈臣〉孫士毅

　　總校官〈臣〉陸費墀


[heading=foreword]
== 帝範序

　　朕聞大德曰生，大寶曰位。辯其上下，樹之君臣，所以撫育黎元，鈞陶庶類，自非克明克哲，允武允文，皇天眷命，歷數在躬，安可以濫握靈圖，叨臨神器！是以翠媯薦唐堯之德，元圭賜夏禹之功。丹字呈祥，周開八百之祚；素靈表瑞，漢啟重世之基。由此觀之，帝王之業，非可以力爭者矣。

昔隋季版蕩，海內分崩。先皇以神武之姿，當經綸之會，斬靈蛇而定王業，啟金鏡而握天樞。然由五嶽含氣，三光戢曜，豺狼尚梗，風塵未寧。朕以弱冠之年，懷慷慨之誌，思靖大難，以濟蒼生。躬擐甲冑，親當矢石。夕對魚鱗之陣，朝臨鶴翼之圍，敵無大而不摧，兵何堅而不碎，剪長鯨而清四海，掃槍而廓八紘。乘慶天潢，登暉璇極，襲重光之永業，繼大寶之隆基。戰戰兢兢，若臨深而禦朽；日慎一日，思善始而令終。

汝以幼年，偏鐘慈愛，義方多闕，庭訓有乖。擢自維城之居，屬以少陽之任，未辯君臣之禮節，不知稼穡之艱難。每思此為憂，未嘗不廢寢忘食。自軒昊以降，迄至周隋，以經天緯地之君，纂業承基之主，興亡治亂，其道煥焉。所以披鏡前蹤，博覽史籍，聚其要言，以為近誡雲耳。

== 帝範卷一

**唐太宗文皇帝撰**

NOTE: 帝者，天之一名。以形體謂之天，以主宰謂之帝。帝者，諦也。言天蕩然，無心忘于物我，公平通逺，舉事審諦。故謂之「帝」，又曰「察道者帝」。又「三皇五帝」。「三王」或曰帝。既天之一名，而以三皇居，先是優於帝而過於天耶。曰：「三皇」不能過天，但優於帝矣。何以為優以遂同天之名。以為優劣耳，何則以五帝有為，而同天三皇無為而同天？以有為無為，故知三皇優也。或曰：「三王抑劣於帝乎」。曰：「三王雖實聖人，但内同天而外，隨時運不得盡其聖用，逐迹為名，故謂之為王也。禮運曰：「大道之行，天下為公。」即帝也，大道既隠，各親其親，即王也。三王亦順帝之則，而不盡故不得，名帝然天之與帝義為一也故繼天則謂之天子其號謂之帝。總三而論，之以帝得其中正矣。皇者，天也。羙也，王者大也。天地人，以一貫三為王天下所法也。王按左氏傳並音于况反範法也，言可以為帝王之法式。故名之「帝範」，以漢孔安國尚書，序曰：「典謨訓誥，誓命之文凡百篇示人主，以軌範也其義同。」

=== 君體第一


NOTE: 君，白虎通曰：「君者，羣也。羣，下所歸心。」又苟卿曰：「君者，儀也。民者，影也。」儀正則影正君者盤也民者水也。盤圓則水圓。君者，源也。源清則流清，源濁則流濁。左傳云：「慶賞刑威，曰：『君體者，治體也。君之所治體勢規模第者，次第也。一者，數之始也。萬物得一以生。老子曰：「聖人抱一為天下式。」故君體為第一也。 ○按荀子，無民者，影也。民者，水也。二語又，君者，源也。作君者，人之源也。

　　夫footnote:[夫音扶語辭後放此]人者，國之先footnote:[易曰有天地然後有萬物有萬物然後有男女有男女然後有夫婦有夫婦然後有父子有父子然後有君臣有君臣然後有上下有上下然後禮義有所錯故大學曰有人此有上所以人者國之先也先者前也凡在前者謂之先〉]，國者，君之本footnote:[國者域也域者居也人民所聚居欲為君者能以徳和民民人樂為之用乃可以為國苟不以徳和民人民離散而不附雖欲為君得乎故聖人云得衆則得國失衆則失國所以國者君之本也]。人主footnote:[主即君也領也主領庶衆]之體，如山嶽焉，高峻而不動footnote:[東漢仲長統傳曰徳重如山嶽山者謂四鎭山之重大者也揚州之㑹稽山青州之沂山幽州之醫無閭山冀州之霍山嶽謂五嶽㤗華衡崧恒也詳見前序註言人君之體當如山嶽之尊崇巍然鎭静故云不動]；如日月焉，貞明而普照footnote:[易曰日月之道貞明者也言若日月正一自然之明晝夜更迭不息於至髙至極之上普徧照燭在下之萬物自然貞一無私向者唯日月焉人君照臨萬方之衆務故取法日月貞明之象耳貞正也]。兆庶之所瞻仰footnote:[卜萬曰億十億曰兆庶衆也凡人君有動作兆億庶衆咸瞻仰以為則而行之也]，天下之所歸往footnote:[易乾鑿度曰王者天下所歸四海之内曰天下孟子曰伯夷辟紂居北海之濵聞文王作興曰盍歸乎來吾聞西伯善養老者大公辟紂居東海之濵聞文王作興曰盍歸乎來吾聞西伯善養老者二老者天下之大老也而歸之是天下之父歸之也天下之父歸之其子焉徃此二者歸徃之明效焉故太宗曉之]。寬大其誌，足以兼包footnote:[志心之所之也人君之志當寛裕廣大與天地同徳包括其區宇㴠容庶物〉]；平正其心足以制斷footnote:[大學曰所謂脩身在正其心者心有所忿懥則不得其正有所好樂則不得其正有所憂患則不得其正有所恐懼則不得其正此言人君心不平正則是非不明心若平正則是非明矣以此制斷事事物物自得其宜矣]。非威德無以致遠footnote:[班固典引曰威靈行於鬼區注云鬼區逺方也威徳者非窮兵黷武慘酷之暴乃應天順民以征不義故能令行禁止天下畏服無逺而不至也]，非慈厚無以懷人footnote:[孔子曰慈可以服衆又書曰安人則恵黎民懐之慈恵愛也懷安保也謂王者撫緌兆民若非慈愛廣厚則成小恵故云非慈厚無以懷人]。撫九族以仁footnote:[商書堯典曰克明俊徳以親九族歐陽夏侯氏謂九族者父族四五属之内為一族父女昆弟適人者與其子為一族已女昆弟適人者與其子為一族已之子適人者與其子為一族母族三母之父姓為一族母之母姓為一族母之昆弟適人者為一族妻族二妻之父姓為一族妻之母姓為一族又唐孔氏說九族者上從髙祖下至元孫凡九族皆為同姓二説不同故並存之太宗言此九族之親長者安之少者懷之愛之勿可驕慢驕慢則離而相怨矣自天子至于庶人惟九族不可不撫愛詩曰綿綿葛藟在河之滸終逺兄弟謂他人父謂他人父終莫我顧此刺平王失禮于親戚也可不誡哉〉]，接大臣以禮footnote:[論語曰君使臣以禮中庸曰敬大臣也體羣臣也又曰敬大臣則不眩體羣臣則士之報禮重]。奉先思孝footnote:[尚書太甲曰奉先思孝以念祖徳為孝先祖先也中庸曰善繼人之志善述人之事者也　奉父勇切]，處位思恭footnote:[太甲篇曰接下思恭以不驕慢為恭下臣下也　處上聲]。傾己勤勞，以行德義footnote:[傾猶抑也已我也即虛已之義不以我為尊不以我為貴不以我為才不以我為智當以孜孜不倦於徳義耳勤孜孜也勞事功曰勞徳者得也得之於道之謂徳義事之冝也裁制事物合宜之謂義]，此乃君之體也footnote:[言若能行此是乃為君之大體矣]。

=== 建親第二

NOTE: 左傳曰：「封建親戚以藩屏周室，親骨肉也。言有天下者，宜樹立藩鎭，骨肉分置之於内外，以相與維持庶無孤削單弱之患。夫水之無本，縱築而亦涸木之，無柢縱溉而亦焦。大厦將興資衆材，而後可成千間之廣。大鵬將翥藉短羽，而後可揚萬里之逺。人君欲為國享萬世無疆之休者，豈可獨立，任其智力者乎。左傳曰：「葛藟猶能庇其根本，故君子以為比况國君乎，固宜建親。」建親之道，不特骨肉之謂也。至如賢徳忠純，明哲通才之君子，建而親之，孰曰：『不可。』」

　　夫六合曠道，大寶重任。曠道不可偏制，故與人共理之；重任不可獨居，故與人共守之。是以封建親戚，以為藩衛，安危同力，盛哀一心。遠近相持，親疏兩用。並兼路塞，逆節不生。昔周之興也，割裂山河，分王宗族。內有晉鄭之輔，外有魯衛之虞。故卜祚靈長，歷年數百。秦之季也，棄淳于之策，納李斯之謀。不親其親，獨智其智，顛覆莫恃，二世而亡。斯豈非枝葉不疏，則根柢難拔；股肱既殞，則心腹無依者哉！漢初定關中，誠亡秦之失策，廣封懿親，過於古制。大則專都偶國，小則跨郡連州。末大則危，尾大難掉。六王懷叛逆之誌，七國受鈇鉞之誅。此皆地廣兵強積勢之所致也。魏武創業，暗於遠圖。子弟無封戶之人，宗室無立錐之地。外無維城以自固，內無盤石以為基。遂乃大器保於他人，社稷亡於異姓。語曰：「流盡其源竭，條落則根枯。」此之謂也。

　　夫封之太強，則為噬臍之患；致之太弱則無固本之基。由此而言，莫若眾建宗親而少力。使輕重相鎮，憂樂是同。則上無猜忌之心，下無侵冤之慮。此封建之鑒也。斯二者，安國之基。

　　君德之宏，唯資博達。設分縣教，以術化人。應務適時，以道制物。

　　術以神隱為妙，道以光大為功。括蒼旻以體心，則人仰之而不測；包厚地以為量，則人循之而無端。蕩蕩難名，宜其宏遠。且敦穆九族，放勛流美於前；克諧烝乂，重華垂譽於後。無以奸破義，無以疏間親。察之以德，則邦家俱泰，骨肉無虞，良為美矣。

=== 求賢第三

NOTE: 周書隂符曰：「凡治國有三常。一曰：『君以舉賢為常。』二曰：『官以任賢為常。』三曰：『士以敬賢為常。』」夫然，雖百代，可知也。故孟子曰：「堯舜之仁，不徧愛人，急親賢也。」是以，知聖人之言，不徒發也。苟賢人在野，小人在朝，縱欲以仁。徧愛人亦狭矣。惟急親賢，而牧之天下，俱得其所也。用賢人，則邦家泰。用小人，則邦家否。其泰否之，一吉一凶，在易焉。泰之彖辭曰：「泰，小徃大來，吉，亨。」則是天地交，而萬物通也。上下交而其志同也。内陽而外隂，内健而外順。内君子而外小人。君子道長，小人道消也。泰之時，天地交，萬物通。天地之極治也。上下交其志同，天下之極治也。極治之功幽，至於天地明，至於人物無不泰而通焉。孰為此者，聖人也。聖人何道臻此？一言以蔽之曰：「進君子，退小人，而已。消之，長之，在彼。内之，外之，在此。又初九曰：「㧞茅連茹，以其彚征，吉。」夫一茅㧞衆根隨一賢舉衆俊歸堯舉一舜乃得十六舜舜舉一禹乃得九禹所謂彚征吉者此也至否之彖辭曰否之匪人不利君子貞大徃小來則是天地不交而萬物不通也上下不交而天下無邦也内隂而外陽内柔而外剛内小人而外君子小人道長君子道消也楊誠齋曰易中極亂之辭未有痛于否之彖者匪人一用何遽至於天地不交而萬物不通上下不交而天下無邦乎萬物不通則舉天下而為墟天下無邦則舉國家而為墟小人之禍何若是烈也盖秦亡于李斯上書之日漢替于張禹談經之時咸陽之煨燼地皇之塗炭何必見而後悟哉此說深得㫖矣天地之氣不交則萬物無生成之理上下之義不交則天下無邦國之道建邦國所以為治也上施政以治民民戴君而從命上下相交所以治安也今上下不交是天下無邦國之道也隂柔在内陽剛在外君子徃處于外小人来處于内小人道長君子道消之時六二六三包承包羞小人柔諂之資不中不正並包羣小而為宗相援相引濫謀邪慮何所不至也如林甫仙客許史石顯鄭朋五鹿極小人之情狀以䘮國危君此小人之烈酷更有何加焉嗚呼聖君觀此否泰安危之道可不慎歟可不誡歟是不可不求賢也能求賢則必得君子荀子曰天地生君子君子理天地君子者天地之参也萬物之統也民之父母也無君子則天地不理禮義不統上無君師下無父母夫是之謂至亂如用及君子必至泰矣

　　夫國之匡輔，必待忠良。任使得人，天下自治。故堯命四嶽，舜舉八元，以成恭己之隆，用贊欽明之道。士之居世，賢之立身，莫不戢翼隱鱗，待風雲之會；懷奇蘊異，思會遇之秋。是明君旁求俊乂，博訪英賢，搜揚側陋。不以卑而不用，不以辱而不尊。昔伊尹，有莘之媵臣；呂望，渭濱之賤老。夷吾困於縲紲；韓信弊於逃亡。商湯不以鼎俎為羞，姬文不以屠釣為恥，終能獻規景毫，光啟殷朝；執旌牧野，會昌周室。

　　齊成一匡之業，實資仲父之謀；漢以六合為家，是賴淮陰之策。

　　故舟航之絕海也，必假橈楫之功；鴻鵠之淩雲也，必因羽翮之用；帝王之為國也，必藉匡輔之資。故求之斯勞，任之斯逸。照車十二，黃金累千，豈如多士之隆，一賢之重。此乃求賢之貴也。

== 帝範卷二

=== 審官第四

NOTE: 尚書臯陶曰都在知人在安民禹曰吁咸若時惟帝其難之知人則哲能官人安民則恵黎民懐之能哲而恵何憂乎驩兠何遷乎有苗何畏乎巧言令色孔壬頴逹曰臯陶述此脩身親人之道以吿禹在於知人善惡擇而信任之在於能安下民為政以安定之也禹驚而答曰吁人君如是能知人能安民惟帝堯猶其難之况餘人乎知人善惡則為大智能用官得其人矣能安下民則為恵政衆民皆歸之矣此不易之理也若帝堯能智而恵則當朝無姦佞何憂懼於驩兠之佞而放之何須逺遷徙於有苗之君何畏懼於彼巧言令色為甚佞之人故古之明王用人必先六徴以嘗之然後任之任人之際國之安危民之休戚繫焉故不可不審也審者謂核其實也若核而得實信使守約亷使分財官無曠職職無虚位務成而事濟矣惟人君不可不慎審其官也左傳曰舉不失職官不易方亦審官之義也

　　夫設官分職，所以闡化宣風。故明主之任人，如巧匠之制木，直者以為轅，曲者以為輪；長者以為棟梁，短者以為栱角。無曲直長短，各有所施。明主之任人，亦由是也。智者取其謀，愚者取其力；勇者取其威，怯者取其慎，無智、愚、勇、怯，兼而用之。故良匠無棄材，明主無棄士。不以一惡忘其善；勿以小瑕掩其功。割政分機，盡其所有。然則函牛之鼎，不可處以烹雞；捕鼠之貍，不可使以搏獸；一鈞之器，不能容以江漢之流；百石之車，不可滿以斗筲之粟。何則大非小之量，輕非重之宜。

　　今人智有短長，能有巨細。或蘊百而尚少，或統一而為多。有輕才者，不可委以重任；有小力者，不可賴以成職。委任責成，不勞而化，此設官之當也。斯二者治亂之源。

　　立國制人，資股肱以合德；宣風道俗，俟明賢而寄心。列宿騰天，助陰光之夕照；百川決地，添溟渤之深源。海月之深朗，猶假物而為大。君人禦下，統極理時，獨運方寸之心，以括九區之內，不資眾力何以成功？必須明職審賢，擇材分祿。得其人則風行化洽，失其用則虧教傷人。故雲則哲惟難，良可慎也！

=== 納諫第五

NOTE: 尚書曰朝夕納諌以輔台徳又傳說謂髙宗曰惟木從䋲則直后從諫則聖后聖臣不命其承疇敢不祗若王之休命言木以繩直君以諫聖明君能受諫則臣不待其命承意而諫之也既王能如此則誰敢不敬順王之美命而諫者乎是以堯舜衢室之問總章之訪以来天下之諫以通天下之情故至聖至明以配天也至如桀紂拒諌飾非直至於焚放而不自覺者誠可悲哉疇誰也祗敬也休美也

　　夫王者，高居深視，虧聽阻明。恐有過而不聞，懼有闕而莫補。所以設鞀樹木，思獻替之謀；傾耳虛心，佇忠正之說。言之而是，雖在仆隸芻蕘，猶不可棄也；言之而非，雖在王侯卿相，未必可容。其義可觀，不責其辯；其理可用，不責其文。至若折檻懷疏，標之以作戒；引裾卻坐，顯之以自非。故雲忠者瀝其心，智者盡其策。臣無隔情於上，君能遍照於下。

　　昏主則不然，說者拒之以威；勸者窮之以罪。大臣惜祿而莫諫，小臣畏誅而不言。恣暴虐之心，極荒淫之誌。其為雍塞，無由自知。以為德超三皇，材過五帝。至於身亡國滅，豈不悲哉！此拒諫之惡也。

=== 去讒第六

NOTE: 䜛譖也荀子曰傷良曰䜛小雅青蠅詩云營營青蠅止于樊豈弟君子無信䜛言孔疏云營營徃來也彼營營徃來青蠅之蟲汙白使黒汙黒使白乃變亂白黒不可近之當逺去之于外止于藩籬之上無令在宫室之内也此周之大夫厭幽王聴信䜛佞作此詩以刺之也以青蠅喻䜛佞之人變亂善惡如青蠅變亂黒白也不可親之當棄于荒野之外無令在朝廷之上䜛人為害如此故云樂易之君子無信䜛言也昔魯欲使樂正子為政孟子聞之喜而不寐公孫丑曰樂正子彊乎曰否有知慮乎曰否多聞識乎曰否然則奚為喜而不寐曰其為人也好善好善足乎曰好善優於天下而况魯國乎夫苟好善則四海之内皆将輕千里而來告之以善夫苟不好善則人將曰訑訑予既已知之矣訑訑之聲音顔色拒人於千里之外士止於千里之外則䜛諂面諛之人至矣與䜛諂面諛之人居國欲治可得乎以此觀之善䜛進退治亂可見矣

　　夫讒佞之徒，國之蟊賊也。爭榮華於旦夕，競勢利於市朝。以其諂諛之姿，惡忠賢之在己上；奸邪之誌，恐富貴之不我先。朋黨相持，無深而不入；比同相習，無高而不升。令色巧言，以親於上；先意承旨，以悅於君。朝有千臣，昭公去國而不悟；弓無九石，寧一終身而不知。

　　以疏間親，宋有伊戾之禍；以邪敗正，楚有郤宛之誅。斯乃暗主庸君之所迷惑，忠臣孝子之可泣冤。故藂蘭欲茂，秋風敗之；王者欲明，讒人蔽之。此奸佞之危也。斯二者，危國之本。

　　砥躬礪行，莫尚於忠言；敗德敗正，莫逾於讒佞。今人顏貌同於目際，猶不自瞻，況是非在於無形，奚能自睹？何則飾其容者，皆解窺於明鏡，修其德者，不知訪於哲人。詎自庸愚，何迷之甚！良由逆耳之辭難受，順心之說易從。彼難受者，藥石之苦喉也；此易從者，鴆毒之甘口也！明王納諫，病就苦而能消；暗主從諛，命因甘而致殞。可不誡哉！可不誡哉！


== 帝範卷三



=== 誡盈第七

NOTE: 易豐卦彖辭曰日中則昃月盈則食此聖人當豐盛之時憂懼之辭也盖日中者昃所倚月盈者食所伏必然之理人君居至髙至極之位乃豐盛之象固當憂懼守中不至過極則可不然必有傾危之機發矣所以晋武帝不知憂懼則有身後之亂唐元宗不知憂懼則有末年之變知憂其惟堯舜之敬戒禹湯之罪已文王之無逸乎事事物物纔到盈處無有不變音非聖君賢人孰能持盈哉或問揚子持滿曰㧖欹㧖者抑也猶抑損之也言持滿者當自損抑以正其欹不然則覆矣欹欹器也昔孔子入魯桓公廟見有欹器焉曰宥坐之器也虚則欹中則正滿則覆使弟子著水以驗之信然孔子喟然嘆曰吁惡有滿而不覆者哉子路曰敢問持滿有道乎孔子曰聰眀聖知守之以愚功被天下守之以讓勇力撫世守之以怯富有四海守之以謙此所謂挹而損之之道也故太宗達此理而告誡之耳盈滿也欲抑滿得中實難但滿而不溢斯可矣　㧖於革反

　　夫君者，儉以養性，靜以修身。儉則人不勞，靜則下不擾。人勞則怨起，下擾則政乖。人主好奇技淫聲、鷙鳥猛獸，遊幸無度，田獵不時。如此則徭役煩，徭役煩則人力竭，人力竭則農桑廢焉。人主好高臺深池，雕琢刻鏤，珠玉珍玩，黼黻絺綌。如此則賦斂重，賦斂重則人才遺，人才遺則饑寒之患生焉。亂世之君，極其驕奢，恣其嗜欲。土木衣緹繡，而人裋褐不全；犬馬厭芻豢，而人糟糠不足。故人神怨憤，上下乖離，佚樂未終，傾危已至。此驕奢之忌也。

=== 崇儉第八

NOTE: 夫儉者去奢從約之謂豐國富民之本也考諸今古創業垂統之君莫不以儉約而興敗國䘮身之主莫不以奢侈而亡其興亡成敗載諸簡册昭昭然可為鑒矣故太宗以儉居戒盈之先豈無意哉雖然儉固近於吝矣儉不中禮是為吝也雖有周公才美驕吝猶不足觀况其他乎此所以蜉蝣刺其好奢蟋蟀刺不中禮也然則其何以行之哉曰語不云乎菲飲食而致孝乎鬼神惡衣服而致美乎黻冕卑宫室而盡力乎溝洫此是眀王之盛徳至聖之格言依而行之吾無間然矣〉

　　夫聖世之君，存乎節儉。富貴廣大，守之以約；睿智聰明，守之以愚。不以身尊而驕人，不以德厚而矜物。茅茨不剪，采椽不斫，舟車不飾，衣服無文，土階不崇，大羹不和。非憎榮而惡味，乃處薄而行儉。

　　故風淳俗樸，比屋可封。斯二者，榮辱之端。奢儉由人，安危在己。五關近閉，則嘉命遠盈；千欲內攻，則兇源外發。是以丹桂抱蠹，終摧榮耀之芳；朱火含煙，遂郁淩雲之焰。以是知驕出於誌，不節則誌傾；欲生於心，不遏則身喪。故桀紂肆情而禍結，堯舜約己而福延，可不務乎？

=== 賞罰第九

NOTE: 酬功曰：「賞」黜罪曰罰周禮曰刑賞以馭其威賞罰國之大柄也左傳曰善為國者賞不僭而刑不濫賞僭則福及滛人刑濫則懼及善人又漢書曰賞及無功無以勸善罰及無罪無以懲惡惟賞與罰不可不當賞一人而天下恱者賞之罰一人而天下懼者罰之賞罰又當必信也有功者雖讎亦必賞有罪者雖親亦必罰故孔子曰治國制民不隠其親此之謂也惟知此則大道之行天下為公矣惟天下之至公其聖王能之○按注末句疑有錯誤

　　夫天之育物，猶君之禦眾。天以寒暑為德，君以仁愛為心。寒暑既調，則時無疾疫；風雨不節，則歲有饑寒。仁愛下施，則人不雕弊；教令失度，則政有乖違。防其害源者，使民不犯其法；開其利本者，使民各務其業。顯罰以威之，明賞以化之。威立則惡者懼，化行則善者勸。適己而妨於道，不加祿焉；逆己而便於國，不施刑焉。故賞者不德君，功之所致也；罰者不怨上，罪之所當也。故《書》曰：無偏無黨，王道蕩蕩。此賞罰之權也。


== 帝範卷四

=== 務農第十

// TODO: This section when enabled will show an XML encoding error
// NOTE: 専力於事，曰：「務」。闢土殖榖，曰：「農」。天生聖人，為天下主，以務農立國，以足食為政。凡一毫便於農者，必極力行之也。嘗觀諸詩，而知周人重農之意矣。詩曰：「曾孫来止，以見君之尊嚴。出入田畝，而不為屈也。」又曰：「嘗其㫖否，以見田畯之官，相忘豆觴，而不為恥也。」夫櫛風沐雨，莫勞乎農。沾體塗足，莫賤乎農。周之君臣，從事於襏襫之間，交孚於閭里之所，則當時為農者，安得不相勸勉哉。然周人之意不止此也。天子所命者農，命官所先者農，朝廷所加恵者農，官府所分理者農。下至州郷閭巷，婦人女子，賤𨽻小夫，歌詠讃頌亦無一不在農，噫盛矣！夫自後世民不里居農，非前世之農勸相之方視為末務，去而為㳺手棄而為末作，散而為諸侯之食客，聚而為山澤之盗賊。漢復古意多方勸率免其租以優之設其科以貴之民未知種麥則勸之種麥民未知養苗則教之養苗春事欲作則鑄耕種之器田務正殷則不行發卒令至其法之最良者則自天子而下無不以農為務故國彊永而民富康也嗚呼有國家者詎可不務農哉不務則惰惰則廢廢則曠曠而民至逰矣記曰國無曠土則食無逰民至於土曠民逰天下何所倚頼周禮命遂大夫以正嵗簡稼器脩稼政命里宰以嵗時合耦于鋤以治稼穡趨其耕耨行其秩序命遂師廵其稼穡而移用其民以救其時事也太宗之務農實得其本矣。

　　夫食為人天，農為政本。倉廩實則知禮節，衣食足則誌廉恥。故躬耕東郊，敬授人時。國無九歲之儲，不足備水旱；家無一年之服，不足禦寒暑。然而莫不帶犢佩牛，棄堅就偽。求什一之利，廢農桑之基。以一人耕而百人食，其為害也，甚於秋螟。莫若禁絕浮華，勸課耕織，使人還其本，俗反其真，則競懷仁義之心，永絕貪殘之路，此務農之本也。斯二者，制俗之機。

　　子育黎黔，惟資威惠。惠而懷也，則殊俗歸風，若披霜而照春日；威可懼也，則中華懾軏，如履刃而戴雷霆。必須威惠並馳，剛柔兩用，畫刑不犯，移木無欺。賞罰既明，則善惡斯別；仁信普著，則遐邇宅心。勸穡務農，則饑寒之患塞；遏奢禁麗，則豐厚之利興。且君之化下，如風偃草。上不節心，則下多逸誌；君不約己，而禁人為非，是猶惡火之燃，添薪望其止焰；忿池之濁，撓浪欲止其流，不可得也。莫若先正其身，則人不言而化矣。

=== 閱武第十一

NOTE: 閱，簡也。武，兵事也。左傳曰：「戡亂曰『武』：『古者明王，雖享隆平之時，亦未甞不閱武，以備不虞。故周禮大司馬以中春教振旅中夏教茇舎中秋教治兵中冬教大閱大閱者前期羣吏戒衆庶脩戰法也講脩戰法既成専使大司馬掌之有賊賢害民者則伐之暴内陵外者則壇之野荒民散者則削之負固不服者則侵之賊殺其親者則正之放弑其君者則殘之犯令陵政者則杜之外内亂鳥獸行者則㓕之故諸侯聽命蠻夷賔服也壇音善與墠同廢曠之地也。

　　夫兵甲者，國之兇器也。土地雖廣，好戰則人雕；邦國雖安，亟戰則人殆。雕非保全之術，殆非擬寇之方。不可以全除，不可以常用，故農隙講武，習威儀也。是以勾踐軾蛙，卒成霸業；徐偃棄武，遂以喪邦。何則？越習其威，徐忘其備。孔子曰：不教人戰，是謂棄之。故知弧矢之威，以利天下。此用兵之機也。

=== 崇文第十二

NOTE: 崇，尊也，重也。左傳曰：「經緯天地，曰『文』：『夫天以文而化，地以文而生，人以文而㑹，國以文而建，王以文而治，天下以文而安。』反是則不得其正矣。盖文者，乃三才事物中和之氣也，以孝悌忠信仁義禮智廣充之。天理存焉，非絺章繡句，華浮藻麗之文而已。如其崇重絺章繡句，華浮藻麗之文，是為晉成帝，梁武帝，李後主矣。

　　夫功成設樂，治定製禮。禮樂之興，以儒為本。宏風導俗，莫尚於文；敷教訓人，莫善於學。因文而隆道，假學以光身。不臨深溪，不知地之厚；不遊文翰，不識智之源。然則質蘊吳竿，非筈羽不美；性懷辯慧，非積學不成。是以建明堂，立辟雍。博覽百家，精研六藝，端拱而知天下，無為而鑒古今。飛英聲，騰茂實，光於不朽者，其唯學乎？此文術也。斯二者，遞為國用。

　　至若長氣亙地，成敗定乎筆端；巨浪滔天，興亡決乎一陣。當此之際，則貴幹戈而賤庠序。及乎海嶽既晏，波塵已清，偃七德之餘威，敷九功之大化。當此之際，則輕甲冑而重詩書。是知文武二途，舍一不可，與時優劣，各有其宜。武士儒人，焉可廢也。

　　此十二條者，帝王之大綱也。安危興廢，鹹在茲焉。

　　古人有云，非知之難，惟行之不易；行之可勉，惟終實難。是以暴亂之君，非獨明於惡路；聖哲之主，非獨見於善途。良由大道遠而難遵，邪徑近而易踐。小人俯從其易，不得力行其難，故禍敗及之；君子勞處其難，不能力居其易，故福慶流之。故知禍福無門，惟人所召。欲悔非於既往，惟慎禍於將來。當擇聖主為師。毋以吾為前鑒。取法於上，僅得為中；取法於中，故為其下。自非上德，不可效焉。吾在位以來，所制多矣。奇麗服，錦繡珠玉，不絕於前，此非防欲也；雕楹刻桷，高臺深池，每興其役，此非儉誌也；犬馬鷹鶻，無遠必致，此非節心也；數有行幸，以亟勞人，此非屈己也。斯事者，吾之深過，勿以茲為是而後法焉。但我濟育蒼生其益多，平定寰宇其功大，益多損少，人不怨；功大過微，德未虧。然猶之盡美之蹤，於焉多愧；盡善之道，顧此懷慚。況汝無纖毫之功，直緣基而履慶？若崇善以廣德，則業泰身安；若肆情以從非，則業傾身喪。且成遲敗速者，國基也；失易得難者，天位也。可不惜哉？

