= 帝範（唐·太宗）
:doctype: japanese-industrial-standard
:docseries: A
:docnumber: 1001
:edition: 1
:language: ja
:published-date: 2025-01-15
:copyright-year: 2025
:announced-date: 2025-01-15
:announced-date-ja: 公曆 2025年1月15日
:revision-date: 2025-01-15
:revision-date-ja: 公曆 2025年1月15日
:establishment-date: 685-01-01
:establishment-date-ja: 貞觀二十二年1月1日
:title-main-ja: 帝範
:title-main-en: The Imperial Model
:imagesdir: images
:coverpage-image: images/coverpage.pdf
:backpage-image: images/backpage.pdf
:presentation-metadata-color-header-footer-background: #0b0968
:presentation-metadata-vertical-layout: true
:presentation-metadata-autonumbering-style: japanese
:presentation-metadata-coverpage-header: 早稲田大学図書館　原文本注
:presentation-metadata-backpage-boilerplate-text: 未經許可　不得翻印
:toclevels-pdf: 1
:mn-document-class: jis
:mn-output-extensions: xml,html,doc,pdf,rxl
:local-cache-only:
:publisher-ja: 早稲田大学図書館
:publisher-en: Waseda University Library
:publisher-abbr: WUL
:investigative-organization-ja: 欽定四庫全書
:investigative-organization-en: Investigative Committee for the Compilation of the Complete Library in Four Sections
:investigative-committee: 欽定四庫全書
:investigative-committee-representative-name: 酒井 信介
:investigative-committee-representative-role: 部会長
:affiliation: 日本産業標準調査会 標準第一部会
:contributor_position: 委員会長
:source-proposer-name: 一般財団法人日本規格協会

[heading=foreword]
== 序

此文本源於早稲田大学図書館藏品《帝範臣軌》（兩冊）合刻本，其中《帝範》一冊，於寛文8年（1668）由京都「林和泉掾」出版。

冊中印有「不老菴」「去水 五味均平蔵」和「両□」共三印。

《帝範》共二卷。

《帝範》為唐太宗李世民所撰，共十二篇，為太宗於貞觀二十二年（648）撰寫，賜予太子李治。《帝範》一書，為太宗對太子的教誨，內容包括君臣之道、政治之道、修身之道等，是一部具有極高價值的古代文獻。


[.preface]
== 欽定四庫全書　子部一 提要 帝範四卷　儒家類

　　〈臣〉等謹按帝範十二篇唐太宗貞觀二十二年撰以賜太子新舊唐書皆云四卷晁公武讀書志僅載六篇陳振孫書録解題亦題曰一卷元吳萊謂征雲南僰夷時始得完書攷其事在泰定二年蓋此書宋佚其半元乃復完也唐書藝文志載有賈行注而舊唐書敬宗本紀稱寳歴二年秘書省著作郎韋公肅注是書以進是唐時已有二注今本注無姓名觀其體裁似唐人注經之式而其中時稱楊萬里呂祖謙之言疑元人因舊注而補之其援引頗詳洽而詞不免於煩贅〈臣〉等謹為參攷其誤附列注文之下仍依舊史釐為四卷以復其舊雲乾隆三十八年四月恭校上

　　總纂官〈臣〉紀昀〈臣〉陸錫熊〈臣〉孫士毅

　　總校官〈臣〉陸費墀


== 帝範序

　　朕聞大德曰生，大寶曰位。辯其上下，樹之君臣，所以撫育黎元，鈞陶庶類，自非克明克哲，允武允文，皇天眷命，歷數在躬，安可以濫握靈圖，叨臨神器！是以翠媯薦唐堯之德，元圭賜夏禹之功。丹字呈祥，周開八百之祚；素靈表瑞，漢啟重世之基。由此觀之，帝王之業，非可以力爭者矣。

昔隋季版蕩，海內分崩。先皇以神武之姿，當經綸之會，斬靈蛇而定王業，啟金鏡而握天樞。然由五嶽含氣，三光戢曜，豺狼尚梗，風塵未寧。朕以弱冠之年，懷慷慨之誌，思靖大難，以濟蒼生。躬擐甲冑，親當矢石。夕對魚鱗之陣，朝臨鶴翼之圍，敵無大而不摧，兵何堅而不碎，剪長鯨而清四海，掃槍而廓八紘。乘慶天潢，登暉璇極，襲重光之永業，繼大寶之隆基。戰戰兢兢，若臨深而禦朽；日慎一日，思善始而令終。

汝以幼年，偏鐘慈愛，義方多闕，庭訓有乖。擢自維城之居，屬以少陽之任，未辯君臣之禮節，不知稼穡之艱難。每思此為憂，未嘗不廢寢忘食。自軒昊以降，迄至周隋，以經天緯地之君，纂業承基之主，興亡治亂，其道煥焉。所以披鏡前蹤，博覽史籍，聚其要言，以為近誡雲耳。

== 帝範卷一

**唐太宗文皇帝撰**

NOTE: 帝者，天之一名。以形體謂之天，以主宰謂之帝。帝者，諦也。言天蕩然，無心忘于物我，公平通逺，舉事審諦。故謂之「帝」，又曰「察道者帝」。又「三皇五帝」。「三王」或曰帝。既天之一名，而以三皇居，先是優於帝而過於天耶。曰：「三皇」不能過天，但優於帝矣。何以為優以遂同天之名。以為優劣耳，何則以五帝有為，而同天三皇無為而同天？以有為無為，故知三皇優也。或曰：「三王抑劣於帝乎」。曰：「三王雖實聖人，但内同天而外，隨時運不得盡其聖用，逐迹為名，故謂之為王也。禮運曰：「大道之行，天下為公。」即帝也，大道既隠，各親其親，即王也。三王亦順帝之則，而不盡故不得，名帝然天之與帝義為一也故繼天則謂之天子其號謂之帝。總三而論，之以帝得其中正矣。皇者，天也。羙也，王者大也。天地人，以一貫三為王天下所法也。王按左氏傳並音于况反範法也，言可以為帝王之法式。故名之「帝範」，以漢孔安國尚書，序曰：「典謨訓誥，誓命之文凡百篇示人主，以軌範也其義同。」

=== 君體第一

NOTE: 君，白虎通曰：「君者，羣也。羣，下所歸心。」又苟卿曰：「君者，儀也。民者，影也。」儀正則影正君者盤也民者水也。盤圓則水圓。君者，源也。源清則流清，源濁則流濁。左傳云：「慶賞刑威，曰：『君體者，治體也。君之所治體勢規模第者，次第也。一者，數之始也。萬物得一以生。老子曰：「聖人抱一為天下式。」故君體為第一也。 ○按荀子，無民者，影也。民者，水也。二語又，君者，源也。作君者，人之源也。

　　夫人者，國之先，國者，君之本。人主之體，如山嶽焉，高峻而不動；如日月焉，貞明而普照。兆庶之所瞻仰，天下之所歸往。寬大其誌，足以兼包；平正其心足以制斷。非威德無以致遠，非慈厚無以懷人。撫九族以仁，接大臣以禮。奉先思孝，處位思恭。傾己勤勞，以行德義，此乃君之體也。

=== 建親第二

NOTE: 左傳曰：「封建親戚以藩屏周室，親骨肉也。言有天下者，宜樹立藩鎭，骨肉分置之於内外，以相與維持庶無孤削單弱之患。夫水之無本，縱築而亦涸木之，無柢縱溉而亦焦。大厦將興資衆材，而後可成千間之廣。大鵬將翥藉短羽，而後可揚萬里之逺。人君欲為國享萬世無疆之休者，豈可獨立，任其智力者乎。左傳曰：「葛藟猶能庇其根本，故君子以為比况國君乎，固宜建親。」建親之道，不特骨肉之謂也。至如賢徳忠純，明哲通才之君子，建而親之，孰曰：『不可。』」

　　夫六合曠道，大寶重任。曠道不可偏制，故與人共理之；重任不可獨居，故與人共守之。是以封建親戚，以為藩衛，安危同力，盛哀一心。遠近相持，親疏兩用。並兼路塞，逆節不生。昔周之興也，割裂山河，分王宗族。內有晉鄭之輔，外有魯衛之虞。故卜祚靈長，歷年數百。秦之季也，棄淳于之策，納李斯之謀。不親其親，獨智其智，顛覆莫恃，二世而亡。斯豈非枝葉不疏，則根柢難拔；股肱既殞，則心腹無依者哉！漢初定關中，誠亡秦之失策，廣封懿親，過於古制。大則專都偶國，小則跨郡連州。末大則危，尾大難掉。六王懷叛逆之誌，七國受鈇鉞之誅。此皆地廣兵強積勢之所致也。魏武創業，暗於遠圖。子弟無封戶之人，宗室無立錐之地。外無維城以自固，內無盤石以為基。遂乃大器保於他人，社稷亡於異姓。語曰：「流盡其源竭，條落則根枯。」此之謂也。

　　夫封之太強，則為噬臍之患；致之太弱則無固本之基。由此而言，莫若眾建宗親而少力。使輕重相鎮，憂樂是同。則上無猜忌之心，下無侵冤之慮。此封建之鑒也。斯二者，安國之基。

　　君德之宏，唯資博達。設分縣教，以術化人。應務適時，以道制物。

　　術以神隱為妙，道以光大為功。括蒼旻以體心，則人仰之而不測；包厚地以為量，則人循之而無端。蕩蕩難名，宜其宏遠。且敦穆九族，放勛流美於前；克諧烝乂，重華垂譽於後。無以奸破義，無以疏間親。察之以德，則邦家俱泰，骨肉無虞，良為美矣。

=== 求賢第三

NOTE: 周書《隂符》曰：「凡治國有三常。一曰：『君以舉賢為常。』二曰：『官以任賢為常。』三曰：『士以敬賢為常。』」
夫然，雖百代，可知也。故《孟子》曰：「堯舜之仁，不徧愛人，急親賢也。」
是以知聖人之言，不徒發也。苟賢人在野，小人在朝，縱欲以仁。徧愛人亦狭矣。惟急親賢，而牧之天下，俱得其所也。
用賢人，則邦家泰。用小人，則邦家否。其泰否之，一吉一凶，在易焉。泰之彖辭曰：「泰，小徃大來，吉，亨。」則是天地交，而萬物通也。
上下交，而其志同也。内陽而外隂，内健而外順。内君子而外小人。君子道長，小人道消也。泰之時，天地交，萬物通。天地之極治也。
上下交其志同，天下之極治也。極治之功幽，至於天地明，至於人物無不泰而通焉。孰為此者，聖人也。
聖人何道臻此？一言以蔽之，曰：「進君子，退小人，而已。消之，長之，在彼。内之，外之，在此。又初九曰：「㧞茅連茹，以其彚征，吉。」夫一茅㧞，衆根隨；一賢舉，衆俊歸。堯舉一舜，乃得十六舜。舜舉一禹，乃得九禹。所謂彚征吉者，此也。至否之彖辭曰：「否之匪人，不利君子貞。大徃小來，則是天地不交，而萬物不通也。上下不交，而天下無邦也。内隂而外陽，内柔而外剛，内小人而外君子。小人道長，君子道消也。
《楊誠齋》曰:「《易》中極亂之辭，未有痛于『否』之彖者，『匪人』一用何遽至於『天地不交而萬物不通』。『上下不交而天下無邦』乎？萬物不通，則舉天下而為墟。天下無邦，則舉國家而為墟。小人之禍，何若是烈也。盖秦亡于李斯上書之日，漢替于張禹談《經》之時。咸陽之煨燼，地皇之塗炭，何必見而後悟哉？」
此說深得㫖矣。天地之氣不交，則萬物無生成之理。上下之義不交，則天下無邦國之道。建邦國，所以為治也。上施政以治民，民戴君而從命。上下相交，所以治安也。今上下不交，是天下無邦國之道也。陰柔在内，陽剛在外，君子徃處于外，小人來處于内。小人道長，君子道消之時，六二、六三，包承、包羞，小人柔諂之資，不中不正，並包羣小，而為宗相援相引，濫謀邪慮，何所不至也。如林甫、仙客；許史、石顯，鄭朋、五鹿，極小人之情狀，以喪國危君。此小人之烈酷，更有何加焉。嗚呼！聖君觀此否泰安危之道，可不慎歟？可不誡歟？是不可不求賢也。能求賢則必得君子。《荀子》曰：「天地生君子，君子理天地。君子者，天地之参也。萬物之統也。民之父母也。無君子，則天地不理，禮義不統，上無君師，下無父母。」夫是之謂：「至亂」。如用及，君子必至泰矣。

　　夫國之匡輔，必待忠良。任使得人，天下自治。故堯命四嶽，舜舉八元，以成恭己之隆，用贊欽明之道。士之居世，賢之立身，莫不戢翼隱鱗，待風雲之會；懷奇蘊異，思會遇之秋。是明君旁求俊乂，博訪英賢，搜揚側陋。不以卑而不用，不以辱而不尊。昔伊尹，有莘之媵臣；呂望，渭濱之賤老。夷吾困於縲紲；韓信弊於逃亡。商湯不以鼎俎為羞，姬文不以屠釣為恥，終能獻規景毫，光啟殷朝；執旌牧野，會昌周室。

　　齊成一匡之業，實資仲父之謀；漢以六合為家，是賴淮陰之策。

　　故舟航之絕海也，必假橈楫之功；鴻鵠之淩雲也，必因羽翮之用；帝王之為國也，必藉匡輔之資。故求之斯勞，任之斯逸。照車十二，黃金累千，豈如多士之隆，一賢之重。此乃求賢之貴也。

== 帝範卷二

=== 審官第四

NOTE: 《尚書》臯陶曰：「都！在知人，在安民。」禹曰：「吁！咸若時，惟帝其難之知人則哲，能官人。安民則恵，黎民懐之。能哲而恵，何憂乎驩兠？何遷乎有苗？何畏乎巧言令色？」孔壬頴逹曰：「臯陶述此脩身親人之道，以吿禹，在於知人善惡，擇而信任之，在於能安下民，為政以安定之也。」禹驚而答曰：「吁！人君如是能知人，能安民，惟帝堯。猶其難之况，餘人乎，知人善惡，則為大智。能用官，得其人矣。能安下民，則為恵政，衆民皆歸之矣。此不易之理也。若帝堯能智而恵，則當朝無姦佞，何憂懼於驩兠之佞而放之？何須遠遷徙於有苗之君？何畏懼於彼巧言令色，為甚佞之人故？古之明王，用人必先六徴以嘗之，然後任之。任人之際，國之安危，民之休戚繫焉，故不可不審也。審者，謂核，其實也。若核而得實，信使守約，亷使分財，官無曠職，職無虚位，務成而事，濟矣。惟人君不可不慎審其官也。《左傳》曰：「舉不失職，官不易方，亦審官之義也。」

　　夫設官分職，所以闡化宣風。故明主之任人，如巧匠之制木，直者以為轅，曲者以為輪；長者以為棟梁，短者以為栱角。無曲直長短，各有所施。明主之任人，亦由是也。智者取其謀，愚者取其力；勇者取其威，怯者取其慎，無智、愚、勇、怯，兼而用之。故良匠無棄材，明主無棄士。不以一惡忘其善；勿以小瑕掩其功。割政分機，盡其所有。然則函牛之鼎，不可處以烹雞；捕鼠之貍，不可使以搏獸；一鈞之器，不能容以江漢之流；百石之車，不可滿以斗筲之粟。何則大非小之量，輕非重之宜。

　　今人智有短長，能有巨細。或蘊百而尚少，或統一而為多。有輕才者，不可委以重任；有小力者，不可賴以成職。委任責成，不勞而化，此設官之當也。斯二者治亂之源。

　　立國制人，資股肱以合德；宣風道俗，俟明賢而寄心。列宿騰天，助陰光之夕照；百川決地，添溟渤之深源。海月之深朗，猶假物而為大。君人禦下，統極理時，獨運方寸之心，以括九區之內，不資眾力何以成功？必須明職審賢，擇材分祿。得其人則風行化洽，失其用則虧教傷人。故雲則哲惟難，良可慎也！

=== 納諫第五

NOTE: 《尚書》曰：「朝夕納諌，以輔台徳。」又《傳說》謂髙宗曰：「惟木從䋲，則直。后從諫，則聖后。聖臣不命其承，疇敢不祗，若王之休命。言木以繩直，君以諫聖，明君能受諫，則臣不待其命，承意而諫之也。既王能如此，則誰敢不敬順王之美命而諫者乎？是以堯舜衢室之問，總章之訪以来天下之諫，以通天下之情。故至聖至明以配天也。至如桀紂拒諌，飾非直至於焚放而不自覺者，誠可悲哉！疇誰也祗敬也。休美也。

　　夫王者，高居深視，虧聽阻明。恐有過而不聞，懼有闕而莫補。所以設鞀樹木，思獻替之謀；傾耳虛心，佇忠正之說。言之而是，雖在仆隸芻蕘，猶不可棄也；言之而非，雖在王侯卿相，未必可容。其義可觀，不責其辯；其理可用，不責其文。至若折檻懷疏，標之以作戒；引裾卻坐，顯之以自非。故雲忠者瀝其心，智者盡其策。臣無隔情於上，君能遍照於下。

　　昏主則不然，說者拒之以威；勸者窮之以罪。大臣惜祿而莫諫，小臣畏誅而不言。恣暴虐之心，極荒淫之誌。其為雍塞，無由自知。以為德超三皇，材過五帝。至於身亡國滅，豈不悲哉！此拒諫之惡也。

=== 去讒第六

NOTE: 「䜛」，譖也。荀子曰：「《傷良》曰：「䜛，小雅青蠅。《詩》云：『營營青蠅，止于樊。豈弟君子，無信䜛言。』《孔疏》云：『營營，徃來也。彼營營徃來，青蠅之蟲汙白。使黒汙黒使白，乃變亂白黒。不可近之，當逺去之。于外止于藩籬之上，無令在宫室之内也。此周之大夫厭幽王聴信䜛佞，作此詩以刺之也。以青蠅喻䜛佞之人，變亂善惡，如青蠅變亂黒白也。不可親之，當棄于荒野之外。無令在朝廷之上，䜛人為害如此。故云：「樂易之君子，無信䜛言也。」昔魯欲使樂正子為政，孟子聞之，喜而不寐。公孫丑曰：「樂正子彊乎？」曰：「否，有知慮乎？」曰：「否，多聞識乎？」曰：「否，然則奚為喜而不寐？」曰：「其為人也好善。好善足乎？」曰：「好善，優於天下，而况魯國乎？夫苟好善，則四海之内，皆将輕千里而來告之以善。夫苟不好善，則人將曰『訑訑予，既已知之矣！』訑訑之聲音顔色，拒人於千里之外。士止於千里之外，則䜛諂面諛之人至矣。與䜛諂面諛之人居國，欲治可得乎？以此觀之，善䜛進退，治亂可見矣。」

　　夫讒佞之徒，國之蟊賊也。爭榮華於旦夕，競勢利於市朝。以其諂諛之姿，惡忠賢之在己上；奸邪之誌，恐富貴之不我先。朋黨相持，無深而不入；比同相習，無高而不升。令色巧言，以親於上；先意承旨，以悅於君。朝有千臣，昭公去國而不悟；弓無九石，寧一終身而不知。

　　以疏間親，宋有伊戾之禍；以邪敗正，楚有郤宛之誅。斯乃暗主庸君之所迷惑，忠臣孝子之可泣冤。故藂蘭欲茂，秋風敗之；王者欲明，讒人蔽之。此奸佞之危也。斯二者，危國之本。

　　砥躬礪行，莫尚於忠言；敗德敗正，莫逾於讒佞。今人顏貌同於目際，猶不自瞻，況是非在於無形，奚能自睹？何則飾其容者，皆解窺於明鏡，修其德者，不知訪於哲人。詎自庸愚，何迷之甚！良由逆耳之辭難受，順心之說易從。彼難受者，藥石之苦喉也；此易從者，鴆毒之甘口也！明王納諫，病就苦而能消；暗主從諛，命因甘而致殞。可不誡哉！可不誡哉！


== 帝範卷三



=== 誡盈第七

NOTE: 「易豐」卦《彖辭》曰：「日中則昃，月盈則食。此聖人當豐盛之時，憂懼之辭也。盖日中者，昃所倚；月盈者，食所伏。必然之理。人君居至髙至極之位，乃豐盛之象，固當憂懼守中不至。過極則可不然，必有傾危之機發矣。所以晋武帝不知憂懼，則有身後之亂。唐元宗不知憂懼，則有末年之變。知憂，其惟堯舜之敬戒，禹湯之罪已，文王之無逸乎。事事物物，纔到盈處，無有不變音，非聖君賢人，孰能持盈哉？或問揚子，持滿曰：「㧖、欹、㧖者，抑也。猶抑損之也。言持滿者，當自損抑，以正。其欹不然，則覆矣。欹，欹器也。昔孔子入魯桓公廟，見有欹器焉。曰：「宥坐之器也。虚則欹，中則正，滿則覆。」使弟子著水，以驗之信然。孔子喟然嘆曰：「吁！惡有滿而不覆者哉？」子路曰：「敢問持滿有道乎？」孔子曰：「聰眀聖知，守之以愚。功被天下，守之以讓。勇力撫世，守之以怯。富有四海，守之以謙。」此所謂挹而損之之道也。故太宗達此理，而告誡之耳。盈，滿也。欲抑滿得中實難，但滿而不溢，斯可矣。「㧖：於革反」

　　夫君者，儉以養性，靜以修身。儉則人不勞，靜則下不擾。人勞則怨起，下擾則政乖。人主好奇技淫聲、鷙鳥猛獸，遊幸無度，田獵不時。如此則徭役煩，徭役煩則人力竭，人力竭則農桑廢焉。人主好高臺深池，雕琢刻鏤，珠玉珍玩，黼黻絺綌。如此則賦斂重，賦斂重則人才遺，人才遺則饑寒之患生焉。亂世之君，極其驕奢，恣其嗜欲。土木衣緹繡，而人裋褐不全；犬馬厭芻豢，而人糟糠不足。故人神怨憤，上下乖離，佚樂未終，傾危已至。此驕奢之忌也。

=== 崇儉第八

NOTE: 夫儉者，去奢，從約之謂。豐國富民之本也。考諸今古創業垂統之君，莫不以儉約而興。敗國䘮身之主，莫不以奢侈而亡。其興亡成敗，載諸簡册昭昭然，可為鑒矣。故太宗以儉居戒盈之先，豈無意哉？雖然儉，固近於吝矣。儉不中禮，是為吝也。雖有周公才美，驕吝猶不足觀，况其他乎？此所以蜉蝣刺其好奢，蟋蟀刺不中禮也。然則其何以行之哉。曰《語》不云乎：「菲飲食，而致孝乎鬼神。惡衣服，而致美乎黻冕。卑宫室，而盡力乎溝洫。」此是眀王之盛徳，至聖之格言，依而行之，吾無間然矣。

　　夫聖世之君，存乎節儉。富貴廣大，守之以約；睿智聰明，守之以愚。不以身尊而驕人，不以德厚而矜物。茅茨不剪，采椽不斫，舟車不飾，衣服無文，土階不崇，大羹不和。非憎榮而惡味，乃處薄而行儉。

　　故風淳俗樸，比屋可封。斯二者，榮辱之端。奢儉由人，安危在己。五關近閉，則嘉命遠盈；千欲內攻，則兇源外發。是以丹桂抱蠹，終摧榮耀之芳；朱火含煙，遂郁淩雲之焰。以是知驕出於誌，不節則誌傾；欲生於心，不遏則身喪。故桀紂肆情而禍結，堯舜約己而福延，可不務乎？

=== 賞罰第九

NOTE: 酬功，曰：「賞」。黜罪，曰：「罰」。《周禮》曰：「刑賞以馭其威。賞罰，國之大柄也。」《左傳》曰：「善為國者賞，不僭而刑。不濫賞僭則福及滛人，刑濫則懼及善人。又《漢書》曰：『賞及無功，無以勸善。罰及無罪，無以懲惡。惟賞與罰，不可不當。賞一人而天下悅者，賞之；罰一人而天下懼者，罰之。賞罰，又當必信也。有功者雖讎，亦必賞；有罪者雖親，亦必罰。故孔子曰：「治國制民，不隠其親。」此之謂也。惟知此則，大道之行天下為公矣。惟天下之至公，其聖王能之。（○ 按注末句疑有錯誤）

　　夫天之育物，猶君之禦眾。天以寒暑為德，君以仁愛為心。寒暑既調，則時無疾疫；風雨不節，則歲有饑寒。仁愛下施，則人不雕弊；教令失度，則政有乖違。防其害源者，使民不犯其法；開其利本者，使民各務其業。顯罰以威之，明賞以化之。威立則惡者懼，化行則善者勸。適己而妨於道，不加祿焉；逆己而便於國，不施刑焉。故賞者不德君，功之所致也；罰者不怨上，罪之所當也。故《書》曰：無偏無黨，王道蕩蕩。此賞罰之權也。


== 帝範卷四

=== 務農第十

// TODO: This section when enabled will show an XML encoding error

NOTE: 専力於事，曰：「務」。
闢土殖榖，曰：「農」。天生聖人，為天下主，以務農立國，以足食為政。凡一毫便於農者，必極力行之也。
嘗觀諸詩，而知周人重農之意矣。詩曰：「曾孫来止，以見君之尊嚴。出入田畝，而不為屈也。」
又曰：「嘗其㫖否，以見田畯之官，相忘豆觴，而不為恥也。」
夫櫛風沐雨，莫勞乎農。沾體塗足，莫賤乎農。周之君臣，從事於襏襫之間，交孚於閭里之所，則當時為農者，安得不相勸勉哉。
然周人之意不止此也。
天子所命者農，命官所先者農，朝廷所加恵者農，官府所分理者農。下至州郷閭巷，婦人女子，賤𨽻小夫，歌詠讃頌亦無一不在農，噫盛矣！
夫自後，世民不里，居農非前。世之農，勸相之方視為末務去，而為㳺手棄而為末作，散而為諸侯之食客，聚而為山澤之盗賊。
漢復古意，多方勸率，免其租以優之，設其科以貴之。民未知種麥，則勸之種麥。民未知養苗，則教之養苗。
春事欲作，則鑄耕種之器田。務正殷，則不行發卒令。至其法之最良者，則自天子而下，無不以農為務故。
國彊永而民富康也。嗚呼！有國家者，詎可不務農哉。不務則惰，惰則廢，廢則曠，曠而民至逰矣。
《記》曰：「國無曠土，則食無逰民至於土。曠民逰，天下何所倚頼？
《周禮》命：「遂大夫以正嵗簡，稼器，脩稼政。」命里宰：「以嵗時合耦于鋤，以治稼穡。」趨其耕耨，行其秩序。命：「遂師廵其稼穡，而移用其民，以救其時事也。」
太宗之務，農實得其本矣。

　　夫食為人天，農為政本。倉廩實則知禮節，衣食足則誌廉恥。故躬耕東郊，敬授人時。國無九歲之儲，不足備水旱；家無一年之服，不足禦寒暑。然而莫不帶犢佩牛，棄堅就偽。求什一之利，廢農桑之基。以一人耕而百人食，其為害也，甚於秋螟。莫若禁絕浮華，勸課耕織，使人還其本，俗反其真，則競懷仁義之心，永絕貪殘之路，此務農之本也。斯二者，制俗之機。

　　子育黎黔，惟資威惠。惠而懷也，則殊俗歸風，若披霜而照春日；威可懼也，則中華懾軏，如履刃而戴雷霆。必須威惠並馳，剛柔兩用，畫刑不犯，移木無欺。賞罰既明，則善惡斯別；仁信普著，則遐邇宅心。勸穡務農，則饑寒之患塞；遏奢禁麗，則豐厚之利興。且君之化下，如風偃草。上不節心，則下多逸誌；君不約己，而禁人為非，是猶惡火之燃，添薪望其止焰；忿池之濁，撓浪欲止其流，不可得也。莫若先正其身，則人不言而化矣。

=== 閱武第十一

NOTE: 閱，簡也。武，兵事也。左傳曰：「戡亂，曰『武』」。古者明王，雖享隆平之時，亦未甞不閱武，以備不虞。故《周禮》大司馬以：中春教振旅，中夏教茇舎，中秋教治兵，中冬教大閱。大閱者，前期羣吏，戒衆庶脩戰法也。講脩戰法既成，専使大司馬掌之有賊賢害民者，則伐之暴。内陵外者，則壇之野荒。民散者，則削之負固。不服者，則侵之。賊殺其親者，則正之。放弑其君者，則殘之犯令。陵政者，則杜之外。内亂鳥獸行者，則㓕之。故諸侯聽命，蠻夷賔服也。「壇」音「善」與「墠」，同廢曠之地也。

　　夫兵甲者，國之兇器也。土地雖廣，好戰則人雕；邦國雖安，亟戰則人殆。雕非保全之術，殆非擬寇之方。不可以全除，不可以常用，故農隙講武，習威儀也。是以勾踐軾蛙，卒成霸業；徐偃棄武，遂以喪邦。何則？越習其威，徐忘其備。孔子曰：不教人戰，是謂棄之。故知弧矢之威，以利天下。此用兵之機也。

=== 崇文第十二

NOTE: 崇，尊也，重也。左傳曰：「經緯天地，曰『文』：『夫天以文而化，地以文而生，人以文而㑹，國以文而建，王以文而治，天下以文而安。』反是則不得其正矣。盖文者，乃三才事物中和之氣也，以孝悌忠信仁義禮智廣充之。天理存焉，非絺章繡句，華浮藻麗之文而已。如其崇重絺章繡句，華浮藻麗之文，是為晉成帝，梁武帝，李後主矣。

　　夫功成設樂，治定製禮。禮樂之興，以儒為本。宏風導俗，莫尚於文；敷教訓人，莫善於學。因文而隆道，假學以光身。不臨深溪，不知地之厚；不遊文翰，不識智之源。然則質蘊吳竿，非筈羽不美；性懷辯慧，非積學不成。是以建明堂，立辟雍。博覽百家，精研六藝，端拱而知天下，無為而鑒古今。飛英聲，騰茂實，光於不朽者，其唯學乎？此文術也。斯二者，遞為國用。

　　至若長氣亙地，成敗定乎筆端；巨浪滔天，興亡決乎一陣。當此之際，則貴幹戈而賤庠序。及乎海嶽既晏，波塵已清，偃七德之餘威，敷九功之大化。當此之際，則輕甲冑而重詩書。是知文武二途，舍一不可，與時優劣，各有其宜。武士儒人，焉可廢也。

　　此十二條者，帝王之大綱也。安危興廢，皆在茲乎。古人有言，非知之難，惟行之不易；行之可勉，惟終實難。是以暴亂之君，非獨明於惡路；聖哲之主，非獨見於善途。良由大道遠而難遵，邪徑近而易踐。小人俯從其易，不得力行其難，故禍敗及之；君子勞處其難，不能力居其易，故福慶流之。故知禍福無門，惟人所召。欲悔非於既往，惟慎禍於將來。當擇聖主為師。毋以吾為前鑒。取法於上，僅得為中；取法於中，故為其下。自非上德，不可效焉。吾在位以來，所制多矣。奇麗服，錦繡珠玉，不絕於前，此非防欲也；雕楹刻桷，高臺深池，每興其役，此非儉誌也；犬馬鷹鶻，無遠必致，此非節心也；數有行幸，以亟勞人，此非屈己也。斯事者，吾之深過，勿以茲為是而後法焉。但我濟育蒼生其益多，平定寰宇其功大，益多損少，人不怨；功大過微，德未虧。然猶之盡美之蹤，於焉多愧；盡善之道，顧此懷慚。況汝無纖毫之功，直緣基而履慶？若崇善以廣德，則業泰身安；若肆情以從非，則業傾身喪。且成遲敗速者，國基也；失易得難者，天位也。可不惜哉？


== 帝範臣軌⼆書跋

帝範⼆卷臣軌⼆卷也者共成于唐帝。
唐帝受隋氏弊，聰明神武[恶]幾成康，功德兼備。
⾃漢以來未之有。
⾃吁咨都嗟之後，⽽元首股肱互為治道。
故所以帝範臣軌之有作者也。

本朝慱⼠讀之，尤尊之至。
若鐮倉將軍家皆讀之，有助治道久。
何啻中華⽽已哉。
洛⼈林⽩⽔新鏤之梓，
以欲⾏于世良有故哉。⽩⽔需書
其後於是題之。

寛⽂八年秋八⽉⽇

柳⾕散⼈埜⼦苞⽗書

林和泉掾版行


== 件書上卷云

康平三年五月五日點之 札部郎中江匡房

同下卷云

康平三年五月六月點之 治部少丞江匡房
寬治八年七月十六目於楊梅亭點了尤可秘藏而已  藤永實
長寬二年正月廿八目奉授主上已訖 式部大輔藤永範

【樣】安元年七月廿四日椰讀畢此書奉授一代   聖主【已】家之【裏】寶

從三位行宮内鄉兼式部大輔藤永範 建久三年六月十五日御讀畢此  書繼家蹤已及  聖主三代誠是家之秘本也
  正四位下行式部大轉藤朝臣光範

【樣】元二年四月廿三日書寫畢

以二品戶部（永範）本移點畢 菅原淳高

元仁二年三月廿五日 侍御讀畢  翰林學士菅淳高